### ISSUE TITLE
Broken UV export

### ISSUE THREAD

**Issue by Radiomann01** [phonon/blender-vintagestory-json#4]
Export defaults UV coordinates to `1.0, 1.0, 2.0, 2.0` for all faces using Blender 2.93 LTS.

**Comment by Radiomann01** [comment]
After further testing it seems that each exported geometry gets its own set of repeating UV coordinates for each face.

I've attached one of your sample files that I've unwrapped and exported. It seems to have a set of `0.0, 0.0, 0.0, 0.0`
[faputa.txt](https://github.com/phonon/blender-vintagestory-json/files/8563219/faputa.txt)

**Comment by phonon** [comment]
Hi, I'm not seeing the issue on my end. I just merged dev branch changes into master, so try pulling new changes. I'm on Blender 2.93.4. Attached is my .blend file and output. Issue may be texture `#1` getting written with size [0, 0] and when uv coords are a multiple of that, they all result in [u\*0, v\*0] = [0, 0], but I'd need to inspect the .blend file since I'm not seeing this issue.

My export: [faputa.json.txt](https://github.com/phonon/blender-vintagestory-json/files/8563672/faputa.json.txt)
Blend file: https://files.catbox.moe/0dgnq8.blend
Texture file (put in `textures/faputa.png`):
![faputa](https://user-images.githubusercontent.com/6635401/165313793-0690d213-30aa-4257-ad30-1e17a4f28cb0.png)

**Comment by Radiomann01** [comment]
Thanks, I was able to export the .blend you've linked without any issues.
But if I try to export any of the .blends that I've created I still get the same error, even when using 2.93.4 and the updated addon. Which makes me think that I might be doing something wrong.
I've made a simple test file that is a cube unwrapped using smart UV project to help locate the issue.

My export: [Default Cube.json.txt](https://github.com/phonon/blender-vintagestory-json/files/8570371/Default.Cube.json.txt)
Blend file: [https://mega.nz/file/AqJCEDjb#uXPuSCj5yISVXe8eDqiBVjVr6Uq7Lv5rto9aEcUb8dw](https://mega.nz/file/AqJCEDjb#uXPuSCj5yISVXe8eDqiBVjVr6Uq7Lv5rto9aEcUb8dw)
Texture (already packed in .blend):
![UV_test](https://user-images.githubusercontent.com/104355922/165478322-02d92440-86da-4416-a76f-a7440934af27.png)

**Comment by BluntTongs** [comment]
Hello!
I'm experiencing the same issue that Radiomann is going through - Every coordinate set appears to be a repeat of the rest.
